import 'package:flutter/material.dart';
class AppColors {
  AppColors._();
  static const Color primary = Color(0xFF0D7377);
  static const Color primaryLight = Color(0xFF14BDBD);
  static const Color primaryDark = Color(0xFF095C5F);
  static const Color primaryContainer = Color(0xFFE0F4F4);
  static const Color secondary = Color(0xFFF5A623);
  static const Color secondaryContainer = Color(0xFFFFF3DC);
  static const Color surface = Color(0xFFFFFFFF);
  static const Color background = Color(0xFFF8F9FA);
  static const Color surfaceVariant = Color(0xFFF1F3F4);
  static const Color outline = Color(0xFFDDE1E4);
  static const Color textPrimary = Color(0xFF1A1A2E);
  static const Color textSecondary = Color(0xFF6B7280);
  static const Color textTertiary = Color(0xFF9CA3AF);
  static const Color textOnPrimary = Color(0xFFFFFFFF);
  static const Color success = Color(0xFF22C55E);
  static const Color successContainer = Color(0xFFDCFCE7);
  static const Color error = Color(0xFFEF4444);
  static const Color errorContainer = Color(0xFFFEE2E2);
  static const Color warning = Color(0xFFF59E0B);
  static const Color ratingGold = Color(0xFFFBBF24);
  static const Color userBubble = Color(0xFF0D7377);
  static const Color userBubbleText = Color(0xFFFFFFFF);
  static const Color aiBubble = Color(0xFFF1F3F4);
  static const Color aiBubbleText = Color(0xFF1A1A2E);
  static const Color openGreen = Color(0xFF22C55E);
  static const Color closedRed = Color(0xFFEF4444);
  static const Color priceActive = Color(0xFF22C55E);
  static const Color priceInactive = Color(0xFFD1D5DB);
  static const Color shadow = Color(0x1A000000);
  static const Color shadowLight = Color(0x0D000000);
}
